### ISSUE TITLE
Throw error on Not_found not handled

### ISSUE THREAD

**Issue by Gregoirevda** [reasonml-community/error-message-improvement#28]
Shouldn't we avoid having Not_found Exceptions thrown at runtime?

For example:
```
let item = List.find (fun item => item.id === itemId) items
/* Use item */
```
This will pass compilation, at some point you will then have 

> list.js:595 Uncaught (2) ["Not_found", -6, tag: 248]

at runtime. 

It could be avoid from the compilation: Exception Not_found not handled.

**Comment by bassjacob** [comment]
There isn't a good way (that I know of) at the moment to track what exceptions might be thrown, so I don't think there's any way for the compiler to fail.

This is an ongoing discussion at a language level around which API's should return Result and force you to box/unbox their return values and explicitly deal with errors, and which should throw exceptions.

**Comment by Gregoirevda** [comment]
After seeing your talk I think this can actually, as you said, be handled properly with a module that boxes your constructor and public functions. So that e.g. validation should happen before calling another function.

But even then, if you forget to handle some thrown exception, you will have runtime errors :/

**Comment by bassjacob** [comment]
So I, personally, strongly dislike exceptions for exactly that reason. I would prefer a total standard library. 

`find` is a really weird function to throw Not_found rather than returning an option, and I would make an argument that every list method should be total (which is why I end up writing a lot of things using fold_left and fold_right).

But in this case, https://caml.inria.fr/pub/docs/manual-ocaml/libref/List.html ships (since 4.05, so probably not available in bucklescript) a method find_opt that does what you're expecting. The trick is going to be convincing people to be total by default in their libraries

**Comment by bassjacob** [comment]
@chenglou do we intend to have a community position on total functions vs exceptional functions?

**Comment by Gregoirevda** [comment]
@bassjacob  I would also prefer it to be baked into the language! Bind List.find to List.find_opt or hide List.find. Is that possible?

**Comment by chenglou** [comment]
It's possible if you swap out the stdlib or nudge people toward an alternative. The current default is a historical artifact & for perf purposes (exceptions are cheap on the native side, cheaper than boxing) and the initial ocaml folks knew what they were doing. Btw you can pattern-match on exceptions:

```reason
switch (List.find (fun item => item.id === itemId) items) {
| exception Not_found => ...
| result => ...
}
```

 I'll close this since this isn't a compile-time error, so can't be caught and don't have a message. We'll discuss about stdlib somewhere else
