### ISSUE TITLE
This expression has type <x> but an expression was expected of type unit

### ISSUE THREAD

**Issue by glennsl** [reasonml-community/error-message-improvement#30]
Stolen from SO: https://stackoverflow.com/questions/46651717/ocaml-why-i-have-an-error#46651862

See how long it'll take you to figure this puzzle out:

``` reason
let unite x =>
  if (x < 100) {
    x mod 10
  } else if (x >= 100) {
    x mod 100
  };
```

This will cause the compiler to emit the following error:
```
  We've found a bug for you!
  (...)/test.re 4:24-6:3
  
  2 ┆ if (x < 100) {
  3 ┆   x mod 10
  4 ┆ } else if (x >= 100) {
  5 ┆   x mod 100
  6 ┆ };
  
  This is:
    int
  But somewhere wanted:
    unit
```

**SPOILER BELOW**

The problem here is simply that there's a missing else branch. Even if the expression is logically consistent and total, OCaml don't care. According to the compiler, this is a simple matter of types, and you, sir, you have the wrong type!

**Comment by keleshev** [comment]
A controversial idea would be to abandon conditionals without `else` branch, like many other functional languages. This would solve this problem by complaining correctly that you forgot the `else` clause.

**Comment by gasche** [comment]
Note: the upstream OCaml compiler has a PR currently being discussed that prints a better error message in that situation -- this comes out of Arthur Charguéraud's [work on improving type errors](https://arxiv.org/abs/1512.01897):

  Add explanation for errors caused by a type constraint propagated from a keyword
  https://github.com/ocaml/ocaml/pull/1510 by @Armael

With this PR applied, the OCaml compiler returns the following more informative error message:

```
Error: This expression has type int but an expression was expected of type
         unit
       because it is in the result of a conditional with no else branch
```

@chenglou: where can we find the implementation of the better error messages that you wrote? I would be curious to see how easy it would be for you to reuse this work (once Reason is rebased on top of an OCaml version that includes it), and also in general understand how upstream changes may affect (positively or negatively) the life of Reason implementers.

**Comment by chenglou** [comment]
Hello @gasche! That's great to see.

Reason itself supports 4.02.3 to 4.06 and only cares about the AST (using omp). No problem here. Thank you for catering to us =).

The current custom error handling is done in BuckleScript [here](https://github.com/BuckleScript/bucklescript/tree/master/jscomp/super_errors). The readme details the implementation. Basically, I copy over e.g. `typecore.ml` into `super_typecore.ml`, tweak some reporting and register the reporter. Almost equivalent to directly adding `super_typecore.ml` into the ocaml repo. Sometimes I also add a few things to BuckleScript's forked ocaml for convenience.

I just looked at the ocaml PR and the changes should be relatively easy to paste back here too. BuckleScript's still on 4.02.3 (will upgrade soon, we can PM about this somewhere else) so maybe copying the PR into bucklescript would cause some other problems, we'll see.

We can also experiment these kind of changes on BuckleScript itself. The custom printing can be opt-in/out, so shouldn't break many things. Would you like to test it/have us test it?
